name: md_bootstrap_scss_example # change this line to have your library name
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  md_bootstrap_scss:
    git: https://github.com/Dart-Land/md_bootstrap_scss.git
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4+2
  sass_builder: ^2.1.2
